import { test, expect } from '../../shared/fixtures/index.js';
import { skipInHeadless, skipOnMobile } from '../../shared/test-guards.js';

/**
 * M08 reference implementation — generated by Test Agents, then hand-corrected
 * in lecture 8.E after rejecting the healer's band-aid patch.
 *
 * Live TV flows are headed-only (same guardrails as M07 Tubi specs).
 */
test.describe('Tubi Live TV @tubi-live', () => {
  test('Live TV is reachable from the home page', async ({ tubiHome, page }) => {
    skipOnMobile('Live TV menubar navigation is desktop-only');
    skipInHeadless('Tubi Live TV layout needs headed mode');
    await tubiHome.goto();
    await tubiHome.browseMenuItem('Live TV');
    await expect(page).toHaveURL(/\/live/);
    await expect(tubiHome.categoryNav).toBeVisible();
  });

  test('channel guide displays current channel listings', async ({ tubiLiveTv }) => {
    skipInHeadless('Tubi Live TV channel guide needs headed mode');
    await tubiLiveTv.goto();
    await tubiLiveTv.waitForChannelGuideLoaded();
    await expect.poll(async () => tubiLiveTv.channelRows.count()).toBeGreaterThanOrEqual(10);
  });

  test('clicking a channel opens the player', async ({ tubiLiveTv, page }) => {
    skipInHeadless('Tubi Live TV player flow needs headed mode');
    await tubiLiveTv.goto();
    await tubiLiveTv.waitForChannelGuideLoaded();
    await tubiLiveTv.channelRows.first().click();
    await expect(page).toHaveURL(/\/live\/\d+/);
    await expect(page.locator('video')).toBeVisible({ timeout: 15_000 });
  });
});
