#!/usr/bin/env node
/**
 * `npm run brag` — the first-clone wow moment.
 *
 * Runs a real, pre-staged Playwright Test Agents output against Tubi in well
 * under two minutes, so the very first thing a new student runs after
 * `git clone && npm install && npx playwright install` is something that
 * demonstrates what this course is actually about.
 *
 * The plan (`specs/tubi-brag.md`) and the test (`tests/brag/tubi.spec.ts`)
 * are committed pre-staged outputs of the agentic loop — the same convention
 * as the `tests/m07/*` files. This script runs that test live; M07 teaches
 * how the plan and test are generated by the planner/generator/healer.
 */

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const cyan = (s) => `\x1b[36m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const red = (s) => `\x1b[31m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

function step(n, total, title) {
  console.info(`\n${cyan(`[${n}/${total}]`)} ${title}`);
}

const ROOT = resolve(import.meta.dirname, '..');

step(1, 3, 'The plan');
console.info(
  dim('   A Test Agents planner produced specs/tubi-brag.md (pre-staged in this repo).'),
);

step(2, 3, 'The generated test');
console.info(
  dim('   The generator turned that plan into tests/brag/tubi.spec.ts (pre-staged here too).'),
);

step(3, 3, 'Running the generated Tubi test (chromium)');
const result = spawnSync(
  'npx',
  ['playwright', 'test', 'tests/brag/', '--project=chromium', '--reporter=list'],
  { stdio: 'inherit', cwd: ROOT },
);

const reportHint = existsSync(resolve(ROOT, 'playwright-report'))
  ? `Run ${cyan('npm run report')} to open the HTML report.`
  : `Run ${cyan('npm run report')} once a run has produced a report.`;

if (result.status === 0) {
  console.info(
    `\n${green('Done.')}  A real Tubi test, generated by the agentic loop, just ran green.`,
  );
  console.info(`   ${reportHint}`);
  console.info(
    dim(
      '   This was a pre-staged version of the loop. Module M07 teaches you how it actually works.',
    ),
  );
} else {
  console.info(`\n${red('The demo test did not pass.')}`);
  console.info(
    dim(
      '   Tubi is a real production site — if it is unreachable or rate-limiting, re-run in a moment.',
    ),
  );
  console.info(dim('   Make sure `npx playwright install --with-deps chromium` has been run.'));
  process.exit(result.status ?? 1);
}
